name: Build
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
<<<<<<< HEAD
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
=======
          node-version: '18.13'  # Usamos Node.js v18.13 o superior para ser compatible con Angular 17

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli@17.3.8  # Instalamos la versión específica de Angular CLI (17.3.8)

      - name: Install dependencies
        run: npm install  # Instalamos las dependencias del proyecto

      - name: Build the project
        run: npm run build --if-present  # Ejecutamos el build del proyecto

      - name: Run tests with coverage
        run: npm run test -- --code-coverage --watch=false  # Ejecutamos las pruebas con cobertura

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectKey: CristhoperSocalayR_AS222S5_T08_fe
          organization: cristhopersocalayr
          token: ${{ secrets.SONAR_TOKEN }}

>>>>>>> 482b7d15a6ab598e5ffd4c5684cea7534b63f4c4
