name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build --if-present

      - name: Run tests with coverage
        run: npm run test -- --code-coverage --watch=false

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectKey: CristhoperSocalayR_AS222S5_T08_fe
          organization: cristhopersocalayr
          token: ${{ secrets.SONAR_TOKEN }}
