name: docker + sonar

on: 
  push: 
    branches: 
      - develop
  pull_request: 
    types: [opened, synchronize, reopened]

jobs: 
  sonarcloud: 
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0  # Desactivar clonaciones superficiales para mejorar la relevancia del análisis
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '16' # Asegúrate de usar una versión compatible
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dockerize: 
    name: Dockerize Angular Project
    needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chatzurefr:latest .
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/chatzurefr:latest
